name: First Workflow

on: workflow_dispatch

jobs:
  first-job:
    runs-on: ubuntu-latest   # should be "runs-on", not "run-on"
    steps:
      - name: Print Greeting
        run: echo "Hello World"

      - name: Print GoodBye
        run: echo "Done-Bye!"
